name: CI

# Trigger the workflow on push or pull request, but only for the master branch
on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches: [master]

jobs:
  cabal:
    name: ${{ matrix.os }} / ghc ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        ghc:
          - "8.6.5"
          - "8.8.3"
          - "8.10.3"
        include:
          - ghc: "8.10.3"
            os: windows-latest
            continue-on-error: true
          - ghc: "8.10.3"
            os: macOS-latest
            experimental: true
            continue-on-error: true

    env:
      CONFIG: "--enable-tests --enable-benchmarks"

    steps:
    - uses: actions/checkout@v2

    - uses: haskell/actions/setup@v1
      id: setup-haskell-cabal
      name: Setup Haskell
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: "latest"

    - run: cabal v2-update
    - run: cabal v2-freeze $CONFIG

    - uses: actions/cache@v2
      name: Cache cabal-store
      with:
        path: |
          ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
          dist-newstyle
        key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.ghc }}-

    - run: cabal v2-build all $CONFIG
    - run: cabal v2-test all -j1 $CONFIG

  stack:
    name: stack
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: haskell/actions/setup@v1
      name: Setup Haskell Stack
      with:
        stack-version: 'latest'
        enable-stack: true
        stack-no-global: true
        stack-setup-ghc: true

    - uses: actions/cache@v2
      name: Cache ~/.stack
      with:
        path: ~/.stack
        key: ${{ runner.os }}-stack

    - name: Build
      run: |
        stack build --system-ghc --test --bench --no-run-tests --no-run-benchmarks

    - name: Test
      run: |
        stack test --system-ghc -j1
        # we need -j1 because of https://github.com/commercialhaskell/stack/issues/5159
